### ISSUE TITLE
Search Box Component

### ISSUE THREAD

**Issue by ArmanAA** [yuriechan/wasteLookup#10]
Goal is to import this search box from `reactstrap` `Input Group` component.

On click of search box and on `return` press of the keyboard search should occur and populate the search results component...

**Comment by yuriechan** [comment]
Requirements
- [ ] Filter the data by only `keyword`
- [ ] if the user input does not match with any keyword, show no search results 
- [ ] Inquiry must match the query 
(ex. blue => item with keyword `blue bin` should not be shown, blue bin => item that has keyword `blue bin` should be shown)

**Comment by yuriechan** [comment]
@ArmanAA 
>Concern & Suggestion

Problem
- Filtering data only by `keyword` return single result since `keyword` is unique to other data.

Solution
- Filter data not only by `keyword` but also `category` to show multiple results that are relevant to user input.

**Comment by yuriechan** [comment]
Resolved #17
