### ISSUE TITLE
Favorite Icon

### ISSUE THREAD

**Issue by ArmanAA** [yuriechan/wasteLookup#11]
Clicking the favorite icon should add the search result to the favorite list.
On click favorite star turns `yellow`.
Clicking a favorited icon will unfavorite that item and turn start from `yellow` to `white`.

**Comment by yuriechan** [comment]
> Expected Behavior
- Star should be colored in Yellow when faved. When un-faved or by default, star should have no color.
- User can open the fav list to see all the favorited items
- User can unfavorite the item from both the list and search section
 

> Requirements
- [ ] Star should change color when faved/un-faved
- [ ] Modal should appear when fav list is clicked to open
- [ ] Data should be `added/removed` ` to/from` the favorite list when `faved/un-faved`

**Comment by yuriechan** [comment]
Resolved #19

**Comment by yuriechan** [comment]
#28
